using System.Numerics;
using BNLReloadedServer.BaseTypes;
using BNLReloadedServer.ServerTypes;
using BNLReloadedServer.Service;
using Moserware.Skills;

namespace BNLReloadedServer.Database;

public interface IGameInstance
{
    public bool HasLobby();
    public bool IsOver();
    public void LinkGuidToPlayer(uint userId, Guid guid, Guid regionGuid);
    public void UserEnteredLobby(uint userId);
    // For when players leave via alt+f4
    public void PlayerDisconnected(uint userId);
    // For when players leave via disconnect button
    public void PlayerLeftInstance(uint userId, KickReason reason);
    public void RemoveAllFromSquad(ulong squadId, Action<uint>? onRemove = null);
    public void RemoveAllPlayers(Action<uint>? onRemove = null);
    public void NotifyExitToCustom();
    public void SetMap(MapInfo? mapInfo, MapData map);
    public bool IsMapNull();
    public void SetMatchKey(Key matchKey);
    public void RegisterServices(Guid sessionId, Dictionary<ServiceId, IService> services);
    public void RemoveService(Guid sessionId);
    public void CreateLobby(Key gameModeKey, MapInfo? mapInfo);
    public ChatRoom? GetChatRoom(RoomId roomId);
    public Key GetGameMode();
    public bool NeedsBackfill();
    public (Dictionary<uint, Rating> team1, Dictionary<uint, Rating> team2) GetTeamRatings();
    public void SendAfkWarning(uint playerId);
    public void SwapHero(uint playerId, Key hero);
    public void UpdateDeviceSlot(uint playerId, int slot, Key? deviceKey);
    public void SwapDevices(uint playerId, int slot1, int slot2);
    public void ResetToDefaultDevices(uint playerId);
    public void SelectPerk(uint playerId, Key perkKey);
    public void DeselectPerk(uint playerId, Key perkKey);
    public void SelectSkin(uint playerId, Key skinKey);
    public void SelectRole(uint playerId, PlayerRoleType role);
    public void VoteForMap(uint playerId, Key mapKey);
    public void PlayerReady(uint playerId);
    public void LoadProgressUpdate(uint playerId, float progress);
    public void StartMatch(ICollection<PlayerLobbyState> playerList);
    public void SendUserToZone(uint playerId);
    public void PlayerEnterScene(uint playerId);
    public void PlayerZoneReady(uint playerId);
    public void UnitMoved(uint unitId, ulong moveTime, ZoneTransform transform);
    public void BuildRequest(ushort rpcId, uint playerId, BuildInfo buildInfo, IServiceZone builderService);
    public void CancelBuildRequest(uint playerId);
    public void EventBroadcast(ZoneEvent zoneEvent);
    public void SwitchGear(ushort rpcId, uint playerId, Key gearKey, IServiceZone switcherService);
    public void StartReload(ushort rpcId, uint playerId, IServiceZone reloaderService);
    public void Reload(ushort rpcId, uint playerId, IServiceZone reloaderService);
    public void ReloadEnd(uint playerId);
    public void ReloadCancel(uint playerId);
    public void CreateProj(uint playerId, ulong shotId, ProjectileInfo projInfo);
    public void MoveProj(ulong shotId, ulong time, ZoneTransform transform);
    public void DropProj(ulong shotId);
    public void CreateChannel(ushort rpcId, uint playerId, ChannelData channelData, IServiceZone channelService);
    public void EndChannel(uint playerId);
    public void ToolChargeStart(uint playerId, byte toolIndex);
    public void ToolChargeEnd(ushort rpcId, uint playerId, byte toolIndex, IServiceZone chargeService);
    public void DashChargeStart(uint playerId, byte toolIndex);
    public void DashChargeEnd(ushort rpcId, uint playerId, byte toolIndex, IServiceZone dashService);
    public void DashCast(uint playerId, byte toolIndex);
    public void DashHit(uint playerId, byte toolIndex, HitData hitData);
    public void GroundSlamCast(uint playerId, byte toolIndex);
    public void GroundSlamHit(uint playerId, byte toolIndex, HitData hitData);
    public void AbilityCast(ushort rpcId, uint playerId, AbilityCastData castData, IServiceZone abilityService);
    public void UnitProjectileHit(uint unitId, HitData hitData);
    public void SkybeamHit(uint unitId, HitData hitData);
    public void CastRequest(uint playerId, CastData castData);
    public void Hit(ulong time, Dictionary<ulong, HitData> hits);
    public void Fall(uint unitId, float height, bool force);
    public void Pickup(uint playerId, uint pickupId);
    public void SelectSpawnPoint(uint playerId, uint? spawnId);
    public void TurretTarget(uint playerId, uint turretId, uint targetId);
    public void TurretAttack(uint playerId, uint turretId, Vector3 shotPos, List<ShotData> shots);
    public void MortarAttack(uint mortarId, Vector3 shotPos, List<ShotData> shots);
    public void DrillAttack(uint drillId, Vector3 shotPos, List<ShotData> shots);
    public void UpdateTesla(uint teslaId, uint? targetId, List<uint> teslasInRange);
    public void PlayerCommand(uint playerId, Key command);
    public void StartRecall(uint playerId);
    public void Surrender(ushort rpcId, uint playerId, IServiceZone surrenderService);
    public void SurrenderVote(uint playerId, bool accept);
    public void EditorCommand(uint playerId, MapEditorCommand command, bool force);
    public void DebugSpawnSupply(string? blockbusterCardId);
}